TITLE						Merge trips
PROJECT_DIRECTORY           C:\Projects\Repo\Work\SWIFT\data\Dynus_T
REPORT_FILE                      

NEW_TRAJECTORY_FILE     Vehicles.dat

TRAJECTORY_FILE			VehTrajectory
NEW_TRAJECTORY_FILE
TRIP_ADJUSTMENT_FILE
TRIP_PURPOSE_FIELD
VEHICLE_TYPE_FIELD
TRIP_ADJUSTMENT_FIELD
