TITLE						Merge trips
PROJECT_DIRECTORY           C:\Projects\Repo\Work\SWIFT\data\Dynus_T
REPORT_FILE                      

NEW_VEHICLE_ROSTER_FILE     Vehicles.dat

VEHICLE_ROSTER_FILE_1		Vehicles_HBW_AM.dat
VEHICLE_ROSTER_FILE_2		Vehicles_HBW_MD.dat
VEHICLE_ROSTER_FILE_3		Vehicles_HBW_PM.dat
VEHICLE_ROSTER_FILE_4		Vehicles_HBW_OV.dat
VEHICLE_ROSTER_FILE_5		Vehicles_HNW_AM.dat
VEHICLE_ROSTER_FILE_6		Vehicles_HNW_MD.dat
VEHICLE_ROSTER_FILE_7		Vehicles_HNW_PM.dat
VEHICLE_ROSTER_FILE_8		Vehicles_HNW_OV.dat
VEHICLE_ROSTER_FILE_9		Vehicles_NHO_AM.dat
VEHICLE_ROSTER_FILE_10		Vehicles_NHO_MD.dat
VEHICLE_ROSTER_FILE_11		Vehicles_NHO_PM.dat
VEHICLE_ROSTER_FILE_12		Vehicles_NHO_OV.dat
VEHICLE_ROSTER_FILE_13		Vehicles_NHW_AM.dat
VEHICLE_ROSTER_FILE_14		Vehicles_NHW_MD.dat
VEHICLE_ROSTER_FILE_15		Vehicles_NHW_PM.dat
VEHICLE_ROSTER_FILE_16		Vehicles_NHW_OV.dat
VEHICLE_ROSTER_FILE_17		Vehicles_OTHER_AM.dat
VEHICLE_ROSTER_FILE_18		Vehicles_OTHER_MD.dat
VEHICLE_ROSTER_FILE_19		Vehicles_OTHER_PM.dat
VEHICLE_ROSTER_FILE_20		Vehicles_OTHER_OV.dat
